# This is a basic workflow to help you get started with Actions

name: Run ViConDAR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 # push:
   # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    name: Run  MAtlab
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run ViConDAR
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: Main
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      # Runs a set of commands using the runners shell
      - name: Run python script
        uses: matlab-actions/run-command@v1
        with:
          command: ./Main/ViConDAR.m

